name: CI

on:
  push:
    branches: [ master ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(node -e "console.log(require('./package.json').version)")        
      - name: Publish
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: fonoster/webui
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          workdir: .
          tags: "latest, ${{ steps.get_version.outputs.VERSION }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}    
          script: |
            doctl compute ssh console
            cd /opt/fonoster
            # Stopping all containers
            docker-compose down
            # Removing all images
            docker system prune -fa
            # Restarting the service
            docker-compose up -d
