name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true

env:
  HOST: "console.fonoster.io"

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: $HOST
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_SSHKEY }}
          passphrase: ${{ secrets.DIGITALOCEAN_PASSPHRASE }}
          script: |
            cd /opt/fonoster
            # Stopping all containers
            docker-compose down
            # Removing all images
              docker system prune -fa
              # Restarting the service
              docker-compose up -d
